include("shared.lua")
include("cl_hud.lua")
include("cl_infection.lua")
include("cl_inventory.lua")
include("cl_containers.lua")
include("cl_factions.lua")
include("cl_npc.lua")
include("cl_surrender.lua")
include("cl_daynight.lua")
include("cl_crafting.lua")
include("cl_harvest.lua")
include("cl_arc9hud.lua")
include("cl_base.lua")
include("cl_parasite.lua")
include("cl_placement.lua")
include("cl_companions.lua")
include("cl_customize.lua")
include("cl_zombietame.lua")
include("cl_admin.lua")
include("cl_access.lua")

-- No spawn menu: Q searches containers and harvests corpses (sv_containers.lua, sv_harvest.lua)
hook.Add("SpawnMenuOpen", "GFR_NoSpawnMenu", function()
	if !GetConVar("gfr_allow_spawnmenu"):GetBool() then return false end
end)
-- ...nor the C context menu (its properties are refused server side too: sv_lockdown.lua)
hook.Add("ContextMenuOpen", "GFR_NoContextMenu", function()
	if !GetConVar("gfr_allow_spawnmenu"):GetBool() then return false end
end)
